# Generated by Django 4.1.1 on 2023-05-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_data', models.CharField(max_length=30)),
                ('bool_data', models.BooleanField()),
            ],
        ),
    ]
