# Generated by Django 4.1.1 on 2023-06-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulletNotemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('key', models.IntegerField()),
            ],
        ),
    ]
