# Generated by Django 4.1.1 on 2023-06-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0002_bulletnotemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletnotemodel',
            name='key',
        ),
    ]
