# Generated by Django 4.1.1 on 2023-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0003_remove_bulletnotemodel_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletnotemodel',
            name='done',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
