# Generated by Django 4.1.1 on 2023-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0004_bulletnotemodel_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bulletnotemodel',
            name='tags',
            field=models.ManyToManyField(to='myap.tag'),
        ),
    ]
