# Generated by Django 4.1.1 on 2023-07-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0005_tag_bulletnotemodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='describe',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
