# Generated by Django 4.1.1 on 2023-08-01 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0006_tag_describe_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletnotemodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
