# Generated by Django 4.1.1 on 2023-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0007_alter_bulletnotemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletnotemodel',
            name='order',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
