# Generated by Django 4.1.1 on 2023-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0008_bulletnotemodel_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='charact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalDescription', models.CharField(max_length=40)),
                ('sexDescription', models.CharField(max_length=40)),
                ('ntrDescription', models.CharField(max_length=40)),
                ('happyDescription', models.CharField(max_length=40)),
                ('angryDescription', models.CharField(max_length=40)),
                ('hightDescription', models.CharField(max_length=40)),
                ('keyWord', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='bulletnotemodel',
            name='date',
            field=models.DateTimeField(default='2023-08-20'),
        ),
        migrations.AlterField(
            model_name='bulletnotemodel',
            name='order',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
