# Generated by Django 4.1.1 on 2023-08-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0009_charact_alter_bulletnotemodel_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charact',
            old_name='ntrDescription',
            new_name='ntrFDescription',
        ),
        migrations.RenameField(
            model_name='charact',
            old_name='sexDescription',
            new_name='ntrMDescription',
        ),
        migrations.AddField(
            model_name='charact',
            name='sexFDescription',
            field=models.CharField(default='...', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charact',
            name='sexMDescription',
            field=models.CharField(default='....', max_length=40),
            preserve_default=False,
        ),
    ]
