# Generated by Django 4.1.1 on 2023-08-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0011_bulletnotemodel_checkday_alter_bulletnotemodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletnotemodel',
            old_name='checkday',
            new_name='checkDay',
        ),
    ]
