# Generated by Django 4.1.1 on 2023-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0012_rename_checkday_bulletnotemodel_checkday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletnotemodel',
            name='checkDay',
        ),
        migrations.AddField(
            model_name='bulletnotemodel',
            name='checkDa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
