# Generated by Django 4.1.1 on 2023-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0013_remove_bulletnotemodel_checkday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletnotemodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
