# Generated by Django 4.1.1 on 2023-09-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0014_alter_bulletnotemodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletnotemodel',
            name='txt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
